### PR TITLE
Add a badge for an irc channel

### PR DESCRIPTION
**Pull request by posix4e**

### CODE REVIEW

**Comment by adamcrume** [comment]
I don't want to start badge collecting on the README.  How about we just point users to the chat room like they do in https://github.com/rust-lang/rust?

**Comment by posix4e** [comment]
I am not sure if I deserve a vote. I appreciate the courtesy. I'm sure it's
just as easy for you to just add it.

On Wed, Jul 13, 2016 at 7:16 PM Adam Crume <notifications@github.com> wrote:

> I don't want to start badge collecting on the README. How about we just
> point users to the chat room like they do in
> https://github.com/rust-lang/rust?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/tensorflow-rust/pull/12#issuecomment-232538847>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAxN2-O5fv6XyD6Z4RDMWV296-SlwToFks5qVZvmgaJpZM4JLsTg>
> .
>
-- 
Sent from my mobile 4045076749
Alex Newman

**Comment by adamcrume** [comment]
I'm the project lead, but this is open source, and I'd rather give everyone a say.  I'll go ahead and add a link to the channel.  (A bit later, though, after I've had a chance to eat. :) )

**Comment by adamcrume** [comment]
P.S.  I meant to say that I want everyone to have a say and a chance to contribute.

**Comment by posix4e** [comment]
project! I guess it is a google project. That's pretty neato.

On Wed, Jul 13, 2016 at 7:32 PM Adam Crume <notifications@github.com> wrote:

> P.S. I meant to say that I want everyone to have a say and a chance to
> contribute.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/tensorflow-rust/pull/12#issuecomment-232540895>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAxN21ga4oMogItweylQUMXjmyuKcFYnks5qVZ-7gaJpZM4JLsTg>
> .
>
-- 
Sent from my mobile 4045076749
Alex Newman

**Comment by adamcrume** [comment]
Well, when I say project, I mean that in general terms.  This isn't an official Google offering.  I don't have an official title or anything; I'm just the guy with admin rights on the GitHub repo.

**Comment by posix4e** [comment]
Understood
On Wed, Jul 13, 2016 at 7:40 PM Adam Crume <notifications@github.com> wrote:

> Well, when I say project, I mean that in general terms. This isn't an
> official Google offering. I don't have an official title or anything; I'm
> just the guy with admin rights on the GitHub repo.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/tensorflow-rust/pull/12#issuecomment-232542031>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAxN26hSpI-RzF9G4aHVfZqofDKMnG_Eks5qVaG0gaJpZM4JLsTg>
> .
>
-- 
Sent from my mobile 4045076749
Alex Newman

**Comment by adamcrume** [comment]
Added a reference to the IRC channel in fd62233.

**Pull request closed without merging**
